[package]
name = "uevent-container-forwarder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kobject-uevent = "0.1"
neli = "0.6.3"
netlink-sys = "0.7"
errno = "*"
